### ISSUE TITLE
SaveException.EntityErrors getter throws NullReferenceException

### ISSUE THREAD

**Issue by markhewett** [Breeze/breeze.sharp#10]
In some cases the` _entityErrors` variable in `SaveException` is not being initialized (in my case, I got client side validation errors because my `RowVersion` field was `null` on new objects - not sure why that is an error for inserts anyway!), causing the `SaveException.EntityErrors` getter to throw a NRE.  This makes it hard to check for entity errors in error handling code.  It should return `null` instead.

**Comment by wardbell** [comment]
You're making good points. Waiting for the tech lead to review.

**Comment by bmperdue** [comment]
Is this a fix to this issue? I tried it and I am still getting the issue on save.

**Comment by steveschmitt** [comment]
Fixed by pull request [#13](https://github.com/Breeze/breeze.sharp/pull/13)
