### ISSUE TITLE
Is this project active

### ISSUE THREAD

**Issue by vko-online** [Breeze/breeze.sharp#11]
last commit from november 2014

**Comment by wardbell** [comment]
Yes it is ... very much so ... although we haven't made changes to the front-end recently as we've been evolving back-end capabilities for both BreezeJS and Breeze#.

**Comment by vko-online** [comment]
please checkout http://stackoverflow.com/questions/29058810/is-there-any-angularjs-asp-net-webapi-odata-breeze-js-typescript-example/29066931#29066931
