### ISSUE TITLE
Exported entity manager refuses to import Enum field

### ISSUE THREAD

**Issue by ProxyTech** [Breeze/breeze.sharp#12]
I have an entity with an enum property. I export the related entity manager (entities and metadata) to a text file, and when attempting to import the same metadata and entities, I receive a cast error "Unable to cast from 'Int32' to 'MyEnumName' ". When examining the exported metadata text, I can see that the enums have been exported as int's (which I would expect). Oddly enough, if I manually change the metadata text to be a string representation of the enum, the import process works fine!

Version: 0.6.0.5

**Comment by steveschmitt** [comment]
Fixed by pull request [#13](https://github.com/Breeze/breeze.sharp/pull/13)
