### ISSUE TITLE
ImportMetadata does not do the same work as FetchMetadata

### ISSUE THREAD

**Issue by nebffa** [Breeze/breeze.sharp#21]
[This guide](http://breeze.github.io/doc-cs/metadata-from-script.html) shows how to import metadata from a string using the `ImportMetadata` method. However, it doesn't do the same work as the `FetchMetadata` method.

Namely, the `FetchMetadata` method ends up calling `new CsdlMetadataProcessor().ProcessMetadata(this, json)` which sets up a bunch of entity configuration. The `ImportMetadata` method does not do this work, and it is not possible to do it in user-code as the `CsdlMetadataProcessor` class is internal. Until this is changed, we'll have to rely on `FetchMetadata`.

**Comment by steveschmitt** [comment]
The `ImportMetadata` method assumes that the metadata will be in [Breeze Metadata format](http://breeze.github.io/doc-cs/metadata-schema.html), while the `FetchMetadata` method allows importing of [CSDL](https://msdn.microsoft.com/en-us/library/jj652004(v=vs.113).aspx) metadata from Entity Framework.

**Comment by nebffa** [comment]
Shouldn't `ImportMetadata` support the CSDL format as well? The reasoning is like so:

1. Something fetches the metadata, creating an entity manager, performing some requests, etc. and cleans up. It caches the metadata for later
2. The next time metadata it can be loaded from the cached location

That's not currently possible because the cached metadata cannot be imported. Is there another way to do this that I'm not thinking about?

**Comment by marcelgood** [comment]
@nebffa `importMetadata` is the complement to `exportMetadata`. What you want to do is very possible. After calling `fetchMetada`, you simply export the metadata to your cache location using `exportMetadata` and then you can import it again using `importMetadata` at a later point. The CSDL format is a bit of a legacy format. It comes from the fact that we initially targeted .NET backends with Breeze, but later added support for many other backends.

**Comment by nebffa** [comment]
Damn, I missed that in the documentation :(. Thanks heaps guys, this is exactly what I'm looking for! Your help is much appreciated @marcelgood @steveschmitt
