### ISSUE TITLE
Any chance for license softening

### ISSUE THREAD

**Issue by weitzhandler** [Breeze/breeze.sharp#26]
Any chance to have the license changed to MIT or anything similar?

**Comment by jtraband** [comment]
It's not a big deal for us either way.  Why the preference for MIT over what we already offer.

**Comment by weitzhandler** [comment]
GPL Affero is too strict.

**Comment by jtraband** [comment]
I will look into it.  We really do want the largest possible community to contribute.

**Comment by weitzhandler** [comment]
Honestly two reasons I don't use Breeze# and didn't even try contributing, 1st reason is it's not MIT, 2nd it didn't support Xamarin.Forms, (UWP, Droid, iOS).

**Comment by weitzhandler** [comment]
Any news?

**Comment by weitzhandler** [comment]
I'm mostly developing private LoB apps, MIT, BSD or MS-PL or the like, are my almost options.
Besides, I understand the projects will need contributions as it's buggy, I prefer contributing to MIT-licensed projects.
Another aspect, why BreezeJs and Breeze server is MIT? It's only Breeze# that's GPLA.

**Comment by jtraband** [comment]
sorry for taking so long.  I agree, I think it makes sense to convert this to MIT. Just give me a couple more days.

**Comment by weitzhandler** [comment]
ping

**Comment by jtraband** [comment]
done... sorry for taking so long...

**Comment by weitzhandler** [comment]
Thank you!
My next project is gonna use Breeze#!
