### ISSUE TITLE
Please make Breeze# multi-platform

### ISSUE THREAD

**Issue by weitzhandler** [Breeze/breeze.sharp#29]
Please support Breeze# in Xamarin apps targeting Droid iOS and UWP, via PCL or .NET Standard.

Cross posted issue with details in [StackOverflow](https://stackoverflow.com/questions/44815750/breeze-for-xamarin-forms-uwp-droid-ios/44992304).

**Comment by MrNikolovski** [comment]
Any update on this? Trying to install breeze# on .Net Standard project but it's not working properly.

**Comment by weitzhandler** [comment]
My advice: give up. Breeze# is totally inactive. Unless you're planning on forking this lib and get work done on your own.

**Comment by weitzhandler** [comment]
Your alternatives are probably [`RESTier`](https://github.com/OData/RESTier) or [`OData`](https://github.com/OData/odata.net) at server side, and [`Simple.OData.Client`](https://github.com/OData/odata.net) at client side.

**Comment by MrNikolovski** [comment]
Looks like it has to be simple.odata.client. Thanks @weitzhandler.

**Comment by steveschmitt** [comment]
.NET Standard 2.0 is supported.
