### ISSUE TITLE
Breeze.Sharp already works in browser - please publish NuGet package for .Net Standard 2.0

### ISSUE THREAD

**Issue by zbigniew-gajewski** [Breeze/breeze.sharp#35]
Ironically **Breeze.Sharp** already works in browser (funny, isn't it). Here is [working example](https://github.com/zbigniew-gajewski/uno-wasm-aspnet-core) based on [Uno/Mono/Wasm](https://platform.uno/).

Although Uno/Wasm prject works perfectly fine with **Breeze.Sharp 0.7.0**, the reference shows warning:
***Breeze.Sharp 0.7.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard, Version=v2.0'. This package may not be fully compatible with your project.***

I know, that **Breeze.Sharp** is not actively maintained, but would it be possible to at least prepare official NuGet package for **.Net standard 2.0** just to get rid of this warning?

**Comment by steveschmitt** [comment]
Breeze.Sharp version 0.8.0 supports .NET Standard 2.0.

**Comment by zbigniew-gajewski** [comment]
Works correctly in WebAssembly (via Uno Platform at least). Thanks!
