### ISSUE TITLE
Breeze.Sharp.BaseEntity inherited model throws the error when using "System.Text.Json".

### ISSUE THREAD

**Issue by kmuthukumar23** [Breeze/breeze.sharp#48]
Hi Team,

Thanks in advance.

I have tried to serialize the model using ‘System.Text.Json’ in Blazor server .NET 5.0 application. And I have inherited the ‘Breeze.Sharp.BaseEntity’ into my model class.  But, when I the application, it throws the following error.

![image](https://user-images.githubusercontent.com/31958591/121689480-455bdd00-cae2-11eb-9d18-f893894d7323.png)

Here is my Code,

    private string SerializeString{ get; set; }

    List<TodoItem> todos = new List<TodoItem>();

    public class TodoItem : Breeze.Sharp.BaseEntity {
        public int Id {
            get { return GetValue<int>(); }
            set { SetValue(value); }
        }

        public string Description {
            get { return GetValue<string>(); }
            set { SetValue(value); }
        }
    }

    protected override void OnInitialized()
    {
        todos = Enumerable.Range(1, 1).Select(x => new TodoItem()
        {
            Id = 1,
            Description = "Description",

        }).ToList();

        JsonSerializerOptions options = new JsonSerializerOptions()
        {
            ReferenceHandler = ReferenceHandler.Preserve
        };

        SerializeString = System.Text.Json.JsonSerializer.Serialize(todos, options);
    }

Also, I have attached the replication sample.

[BlazorApp1.zip](https://github.com/Breeze/breeze.sharp/files/6638550/BlazorApp1.zip)

Can anyone please help me to resolve this?

Thanks...

**Comment by GioviQ** [comment]
Try Newtonsoft

Anyway it's not a Breeze.Sharp issue

**Comment by steveschmitt** [comment]
There might be away to make System.Text.Json serialize the way that Breeze needs it, but for now, use Newtonsoft.Json as @GioviQ suggested.
