### ISSUE TITLE
JsonEntityConverter.ParseObject throws NullReferenceException when Querying

### ISSUE THREAD

**Issue by Kapn** [Breeze/breeze.sharp#49]
When querying for an entity and expanding its parent, if the parent has been modified, breeze.sharp throws a null reference error in Breeze.Sharp.JsonEntityConverter.ParseObject because backingStore is null.

I've modifed the BreezeSharp example app slightly to display this issue here:

https://github.com/Kapn/BreezeSharpBug

In the readme is more information regarding this issue.

**Comment by steveschmitt** [comment]
We'll look into it.  Thanks for the excellent repro!

**Comment by Kapn** [comment]
Hi @steveschmitt, any update on this issue/bug?

**Comment by steveschmitt** [comment]
Ah, no, sorry.  I've been very busy, but will try to look at it soon.

**Comment by steveschmitt** [comment]
Finally fixed in version 0.8.1
