### ISSUE TITLE
BreezeSharp SaveChanges MaxDepth exceeded

### ISSUE THREAD

**Issue by crane476** [Breeze/breeze.sharp#51]
SaveChanges throws a JsonReaderException stating the reader's max depth of 64 has been exceeded when updating very large entities. I noticed the most recent update to Json.Net, version 13.0.1, sets the MaxDepth to 64 by default. If I revert to Json.Net version 12.0.3 no exception is thrown.

**Comment by steveschmitt** [comment]
Thanks for finding this.  Is the exception thrown on the client or server?

**Comment by crane476** [comment]
Sorry for the late response, the exception was thrown on the client. I used fiddler to confirm that the server was returning the correct data.

**Comment by steveschmitt** [comment]
Thanks for the clarification.  It seems the easiest course would be to increase the MaxDepth in Json.Net, if that is possible.

**Comment by crane476** [comment]
It is possible and I have a possible solution. SaveChanges returns a SaveResult, which is the result of `dataServiceAdapter.SaveChanges(entitiesToSave, saveOptions);`. That function calls `JNode.DeserializeFrom()` a few times which is where I think this issue is occurring. `JNode.DeserializeFrom()` uses JsonTextReader, which has the MaxDepth property.

If you change `var reader = new JsonTextReader(textReader);` in Json.cs line 345 to `var reader = new JsonTextReader(textReader) { MaxDepth = 128 };` then it should fix the issue.

 I tried cloning the repo to test this myself, but I couldn't get it to compile on my machine.

**Comment by PusparagSubudhi** [comment]
Hi Was there any solution for this we are facing a similar issue where the ExecuteQuery is giving a maxdepth error. How to solve it?

**Comment by steveschmitt** [comment]
I'll take a look soon, hopefully this weekend.  How can I repro the problem?

**Comment by steveschmitt** [comment]
I added the `MaxDepth = 128` property; this should fix the issue.
